#Importing Libraries

In [4]:
import numpy as np

#Array Attributes

In [5]:
a = np.array([1, 2, 3]) #1D array/ Vector

In [6]:
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(3,)

In [9]:
a.ndim

1

In [10]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(b)

numpy.ndarray

In [13]:
b.shape

(2, 3)

In [14]:
b.ndim

2

In [15]:
c = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [16]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
c.shape, c.ndim

((2, 3, 3), 3)

In [18]:
a.dtype, b.dtype, c.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [19]:
a.size, b.size, c.size #Count elements of each array

(3, 6, 18)

In [20]:
a.nbytes, b.nbytes, c.nbytes

(12, 24, 72)

In [21]:
a.data, b.data, c.data #Shows array memory location

(<memory at 0x000002B8A450D240>,
 <memory at 0x000002B8A41E9A80>)

#Array Creation

In [22]:
array1 = np.array([1, 2, 3], dtype = 'int')

In [23]:
array1

array([1, 2, 3])

In [24]:
zeros = np.zeros((3, 3), dtype = 'int')

In [25]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
ones = np.ones((3, 3), dtype = 'int')

In [27]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
fives = np.full((2, 3), 5, dtype = 'int')

In [29]:
fives

array([[5, 5, 5],
       [5, 5, 5]])

In [30]:
identity = np.identity(3, dtype = 'int') #Creates an nxn identity matrix

In [31]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
eye = np.eye(3, k = 1, dtype = 'int')

In [33]:
eye

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [34]:
arange = np.arange(1, 10, 2, dtype = 'int')

In [35]:
arange

array([1, 3, 5, 7, 9])

In [36]:
linspace = np.linspace(1,10,5)

In [37]:
linspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [38]:
empty = np.empty((1,5), dtype = 'int')
for i in range(5):
    empty[:,i] = i + 1

In [39]:
empty

array([[1, 2, 3, 4, 5]])

#Array Indexing and Slicing

Indexing

In [40]:
arr1 = np.array([1, 2, 3, 4, 5])

In [41]:
arr1

array([1, 2, 3, 4, 5])

In [42]:
print(arr1)

[1 2 3 4 5]


In [43]:
arr1[0], arr1[-5] #2 methods of indexing

(1, 1)

In [44]:
arr2 = np.random.randint(1, 10, size = (3, 3))

In [45]:
print(arr2)

[[3 4 4]
 [2 9 4]
 [7 8 6]]


In [46]:
arr2[1][2], arr2[1, 2] #2 methods of indexing

(4, 4)

In [47]:
arr3 = np.random.randint(1, 10, size = (2, 3, 3))

In [48]:
print(arr3)

[[[3 3 7]
  [4 9 7]
  [9 8 6]]

 [[6 1 5]
  [9 4 1]
  [6 7 2]]]


In [49]:
arr3[0][1][2], arr3[0, 1, 2]

(7, 7)

Slicing

In [50]:
print(arr1)

[1 2 3 4 5]


In [51]:
print(arr1[0:3]) #Slices array upto right before upper index

[1 2 3]


In [52]:
print(arr1[2:])

[3 4 5]


In [53]:
print(arr1[:2])

[1 2]


In [54]:
print(arr2)

[[3 4 4]
 [2 9 4]
 [7 8 6]]


In [55]:
print(arr2[0:2, 0:2]) #Keep the first 2 rows and columns

[[3 4]
 [2 9]]


In [56]:
print(arr2[1:, 1:])   #Keep the last 2 rows and columns

[[9 4]
 [8 6]]


#Manipulating Array Shapes
i)reshape()
ii)resize()
iii)flatten()
iv)revel()
v)defining array shape

reshape()

In [57]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [58]:
print(a)

[[1 2 3]
 [4 5 6]]


In [59]:
a.shape

(2, 3)

In [60]:
a_reshaped = np.reshape(a, (3, 2))

In [61]:
print(a_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [62]:
a_resized = np.resize(a, (3, 3))

In [63]:
print(a_resized)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [64]:
a_resized2 = np.resize(a, (3, 2)) #Using resize() as reshape()

In [65]:
print(a_resized2)

[[1 2]
 [3 4]
 [5 6]]


ravel()

In [66]:
a = np.random.randint(1, 10, (2, 3))

In [67]:
print(a)

[[3 7 1]
 [6 6 5]]


In [68]:
a_raveled = np.ravel(a) #Converts an nD array into a vector(1D)

In [69]:
print(a_raveled)

[3 7 1 6 6 5]


In [70]:
a_raveled[0] = 7 #Changing the raveled array also changes the original array

In [71]:
print(a)

[[7 7 1]
 [6 6 5]]


flatten()

In [72]:
print(a)

[[7 7 1]
 [6 6 5]]


In [73]:
a_flattened = a.flatten() #Returns a copy of the array. Allocates a new memory

In [74]:
print(a_flattened)

[7 7 1 6 6 5]


In [75]:
a_flattened[0] = 100 #Changing the flattened array does not affect the original array

In [76]:
print(a_flattened)

[100   7   1   6   6   5]


In [77]:
print(a)

[[7 7 1]
 [6 6 5]]


#Defining an array shape

In [78]:
print(a)

[[7 7 1]
 [6 6 5]]


In [79]:
a.shape

(2, 3)

In [80]:
a.shape = (3, 2)

In [81]:
a

array([[7, 7],
       [1, 6],
       [6, 5]])

#Stacking

In [82]:
a = np.arange(1, 10).reshape(3, 3)

In [83]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
b = 2*a

In [85]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Horizontal Stacking

In [86]:
np.hstack((a, b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [87]:
np.column_stack((a, b)) #Same as hstack

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [88]:
np.concatenate((a, b), axis = 1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

Vertical Stacking

In [89]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [90]:
np.row_stack((a, b)) #Same as vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [91]:
np.concatenate((a, b), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Depth Stacking

In [92]:
np.dstack((a, b))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])